### ISSUE TITLE
Duda

### ISSUE THREAD

**Issue by Ismael-GT** [Raxex/Tor#1]
He podido encontrar tu repositorio por google, gracias por compartir! Tenía una duda es si puedes subir los archivos "El conocimiento absoluto del mundo by Jeff Herzeleid.rar.torrent" parece ser que nadie lo tiene y no puedo descargarlo o donde puedo encontrarlo?

Muchas gracias de antemano.

**Comment by JFernandez06** [comment]
Yo lo tengo el archivo torrent

**Comment by Ismael-GT** [comment]
Gracias por contestar!, Sobre el contenido descargado, podrías subirlo al repositorio?, no hay seeders en el torrent y no puedo descargarlo 👍
